# Generated by Django 3.0.1 on 2020-02-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentdetailsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='section',
            field=models.CharField(max_length=100),
        ),
    ]
